export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const RESET_LOG_ALERT = "RESET_LOG_ALERT";
export const LOG_OUT = "LOG_OUT";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

// ! ASSET
export const ASSET_REQUEST = "ASSET_REQUEST";
export const ASSET_SUCCESS = "ASSET_SUCCESS";
export const ASSET_ERROR = "ASSET_ERROR";

export const ADD_ASSET_REQUEST = "ADD_ASSET_REQUEST";
export const ADD_ASSET_SUCCESS = "ADD_ASSET_SUCCESS";
export const ADD_ASSET_ERROR = "ADD_ASSET_ERROR";

export const GET_ALL_ASSET_LIST_REQUEST = "GET_ALL_ASSET_LIST_REQUEST";
export const GET_ALL_ASSET_LIST_SUCCESS = "GET_ALL_ASSET_LIST_SUCCESS";
export const GET_ALL_ASSET_LIST_ERROR = "GET_ALL_ASSET_LIST_ERROR";

export const DELETE_ASSET_REQUEST = "DELETE_ASSET_REQUEST";
export const DELETE_ASSET_SUCCESS = "DELETE_ASSET_SUCCESS";
export const DELETE_ASSET_ERROR = "DELETE_ASSET_ERROR";

export const UPDATE_ASSET_REQUEST = "UPDATE_ASSET_REQUEST";
export const UPDATE_ASSET_SUCCESS = "UPDATE_ASSET_SUCCESS";
export const UPDATE_ASSET_ERROR = "UPDATE_ASSET_ERROR";

// * Asset History
export const GET_HISTORY_REQUEST = "GET_HISTORY_REQUEST";
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_ERROR = "GET_HISTORY_ERROR";

export const ADD_HISTORY_REQUEST = "ADD_HISTORY_REQUEST";
export const ADD_HISTORY_SUCCESS = "ADD_HISTORY_SUCCESS";
export const ADD_HISTORY_ERROR = "ADD_HISTORY_ERROR";

//* ASSET SBOM
export const GET_SBOM_REQUEST = "GET_SBOM_REQUEST";
export const GET_SBOM_SUCCESS = "GET_SBOM_SUCCESS";
export const GET_SBOM_ERROR = "GET_SBOM_ERROR";

export const ADD_SBOM_REQUEST = "ADD_SBOM_REQUEST";
export const ADD_SBOM_SUCCESS = "ADD_SBOM_SUCCESS";
export const ADD_SBOM_ERROR = "ADD_SBOM_ERROR";

export const DELETE_SBOM_REQUEST = "DELETE_SBOM_REQUEST";
export const DELETE_SBOM_SUCCESS = "DELETE_SBOM_SUCCESS";
export const DELETE_SBOM_ERROR = "DELETE_SBOM_ERROR";

//* Asset File
export const ADD_FILES_REQUEST = "ADD_FILES_REQUEST";
export const ADD_FILES_SUCCESS = "ADD_FILES_SUCCESS";
export const ADD_FILES_ERROR = "ADD_FILES_ERROR";

export const GET_ASSET_FILES_REQUEST = "GET_ASSET_FILES_REQUEST";
export const GET_ASSET_FILES_SUCCESS = "GET_ASSET_FILES_SUCCESS";
export const GET_ASSET_FILES_ERROR = "GET_ASSET_FILES_ERROR";

export const DELETE_FILES_REQUEST = "DELETE_FILES_REQUEST";
export const DELETE_FILES_SUCCESS = "DELETE_FILES_SUCCESS";
export const DELETE_FILES_ERROR = "DELETE_FILES_ERROR";

//* Asset Details
export const GET_ASSET_DETAILS_REQUEST = "GET_ASSET_DETAILS";
export const GET_ASSET_DETAILS_SUCCESS = "GET_ASSET_DETAILS_SUCCESS";
export const GET_ASSET_DETAILS_ERROR = "GET_ASSET_DETAILS_ERROR";

export const HANDLE_ASSET_DETAILS_CHANGE = "HANDLE_ASSET_DETAILS_CHANGE";
// !COMPANy
export const COMPANY_REQUEST = "GET_COMPANY_REQUEST";
export const COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";
export const COMPANY_ERROR = "COMPANY_ERROR";

export const GET_SELECTED_COMPANY = "GET_SELECTED_COMPANY";
export const HANDLE_COMPANY_NAME_CHANGE = "HANDLE_COMPANY_NAME_CHANGE";

export const HANDLE_COMPANY = "HANDLE_COMPANY";

// !USER DETAILS
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR";

// !PENTEST
export const PENTEST_REQUEST = "PENTEST_REQUEST";
export const PENTEST_SUCCESS = "PENTEST_SUCCESS";
export const PENTEST_ERROR = "PENTEST_ERROR";

export const ADD_PENTEST_REQUEST = "ADD_PENTEST_REQUEST";
export const ADD_PENTEST_SUCCESS = "ADD_PENTEST_SUCCESS";
export const ADD_PENTEST_ERROR = "ADD_PENTEST_ERROR";

export const DELETE_PENTEST_REQUEST = "DELETE_PENTEST_REQUEST";
export const DELETE_PENTEST_SUCCESS = "DELETE_PENTEST_SUCCESS";
export const DELETE_PENTEST_ERROR = "DELETE_PENTEST_ERROR";

export const UPDATE_PENTEST_REQUEST = "UPDATE_PENTEST_REQUEST";
export const UPDATE_PENTEST_SUCCESS = "UPDATE_PENTEST_SUCCESS";
export const UPDATE_PENTEST_ERROR = "UPDATE_PENTEST_ERROR";

// * Scope
export const GET_PENTEST_TAB_DETAILS_REQUEST =
  "GET_PENTEST_TAB_DETAILS_REQUEST";
export const GET_PENTEST_TAB_DETAILS_SUCCESS =
  "GET_PENTEST_TAB_DETAILS_SUCCESS";
export const GET_PENTEST_TAB_DETAILS_ERROR = "GET_PENTEST_TAB_DETAILS_ERROR";

export const ADD_SCOPE_REQUEST = "ADD_SCOPE_REQUEST";
export const ADD_SCOPE_SUCCESS = "ADD_SCOPE_SUCCESS";
export const ADD_SCOPE_ERROR = "ADD_SCOPE_ERROR";

export const UPDATE_SCOPE_REQUEST = "UPDATE_SCOPE_REQUEST";
export const UPDATE_SCOPE_SUCCESS = "UPDATE_SCOPE_SUCCESS";
export const UPDATE_SCOPE_ERROR = "UPDATE_SCOPE_ERROR";

export const DELETE_SCOPE_REQUEST = "DELETE_SCOPE_REQUEST";
export const DELETE_SCOPE_SUCCESS = "DELETE_SCOPE_SUCCESS";
export const DELETE_SCOPE_ERROR = "DELETE_SCOPE_ERROR";

//* findings
export const ADD_FINDINGS_REQUEST = "ADD_FINDINGS_REQUEST";
export const ADD_FINDINGS_SUCCESS = "ADD_FINDINGS_SUCCESS";
export const ADD_FINDINGS_ERROR = "ADD_FINDINGS_ERROR";

export const DELETE_FINDINGS_REQUEST = "DELETE_FINDINGS_REQUEST";
export const DELETE_FINDINGS_SUCCESS = "DELETE_FINDINGS_SUCCESS";
export const DELETE_FINDINGS_ERROR = "DELETE_FINDINGS_ERROR";

export const UPDATE_FINDINGS_REQUEST = "UPDATE_FINDINGS_REQUEST";
export const UPDATE_FINDINGS_SUCCESS = "UPDATE_FINDINGS_SUCCESS";
export const UPDATE_FINDINGS_ERROR = "UPDATE_FINDINGS_ERROR";
// !Emails
export const GET_EMAIL_REQUEST = "GET_EMAIL_REQUEST";
export const GET_EMAIL_SUCCESS = "GET_EMAIL_SUCCESS";
export const GET_EMAIL_ERROR = "GET_EMAIL_ERROR";

// ! Users

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const ADD_USERS_REQUEST = "ADD_USERS_REQUEST";
export const ADD_USERS_SUCCESS = "ADD_USERS_SUCCESS";
export const ADD_USERS_ERROR = "ADD_USERS_ERROR";

export const DELETE_USERS_REQUEST = "DELETE_USERS_REQUEST";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export const DELETE_USERS_ERROR = "DELETE_USERS_ERROR";
